# Data Collection

## Objective

Download historical stock data from Yahoo Finance.

Ticker: RELIANCE.NS

Period: 5 Years

Data Source: Yahoo Finance

In [2]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
import yfinance as yf

ticker = "RELIANCE.NS"

df = yf.download(
    ticker,
    period="5y",
    auto_adjust=False,
    progress=False
)

df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2021-07-01,950.199158,968.203613,979.833374,966.842163,977.456665,12534407
2021-07-02,964.284912,982.556213,984.333008,965.896057,967.765137,14086620
2021-07-05,973.864136,992.316956,993.862976,983.686890,985.971313,11702287
2021-07-06,962.359985,980.594849,991.716980,978.471985,989.894104,10070124
2021-07-07,955.679443,973.787720,981.956299,968.226685,981.956299,10454892

In [11]:
df.tail()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
Date,,,,,,
2026-06-25,2094.699951,2094.699951,2148.500000,2088.000000,2133.600098,4738903
2026-06-26,2094.699951,2094.699951,2094.699951,2094.699951,2094.699951,0
2026-06-29,2097.899902,2097.899902,2105.000000,2071.000000,2090.000000,3412470
2026-06-30,2031.500000,2031.500000,2104.300049,2018.800049,2090.000000,6848411
2026-07-01,1982.599976,1982.599976,2052.000000,1976.800049,2039.900024,4656000

In [5]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 0 entries
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Adj Close, RELIANCE.NS)  0 non-null      float64
 1   (Close, RELIANCE.NS)      0 non-null      float64
 2   (High, RELIANCE.NS)       0 non-null      float64
 3   (Low, RELIANCE.NS)        0 non-null      float64
 4   (Open, RELIANCE.NS)       0 non-null      float64
 5   (Volume, RELIANCE.NS)     0 non-null      float64
dtypes: float64(6)
memory usage: 0.0 bytes