# Exploratory Data Analysis (EDA)

## Objective

Understand the structure of the stock dataset before feature engineering.

Dataset:
RELIANCE_NS.csv

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent

DATA_PATH = BASE_DIR / "data" / "raw" / "RELIANCE_NS.csv"

df = pd.read_csv(DATA_PATH)

In [3]:
df.head()

,Price,Adj Close,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-07-01,950.1991577148438,968.20361328125,979.8333740234375,966.8421630859375,977.4566650390625,12534407
3,2021-07-02,964.2848510742188,982.5562133789062,984.3330078125,965.8960571289062,967.76513671875,14086620
4,2021-07-05,973.8640747070312,992.3169555664062,993.8629760742188,983.6868896484375,985.9713134765625,11702287

In [4]:
df.shape

(1240, 7)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1240 non-null   str
 1   Adj Close  1239 non-null   str
 2   Close      1239 non-null   str
 3   High       1239 non-null   str
 4   Low        1239 non-null   str
 5   Open       1239 non-null   str
 6   Volume     1239 non-null   str
dtypes: str(7)
memory usage: 67.9 KB

In [6]:
df.describe()

,Price,Adj Close,Close,High,Low,Open,Volume
count,1240,1239,1239,1239,1239,1239,1239
unique,1240,1203,1184,1132,1137,1059,1235
top,Ticker,1267.2559814453125,1464.824951171875,1306.0,1151.442138671875,1420.0,0
freq,1,3,4,4,4,6,5

In [7]:
df.columns

Index(['Price', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')