In [1]:
from pathlib import Path
import pandas as pd

In [2]:
BASE_DIR = Path.cwd().parent

FEATURE_PATH = BASE_DIR / "data" / "features" / "HDFCBANK_NS.csv"

df = pd.read_csv(FEATURE_PATH)

df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Return,Log Return,SMA_20,SMA_50,EMA_12,EMA_26,Rolling Volatility,Month,Quarter,Day of Week
0,2021-09-16,768.875,782.150024,768.150024,779.974976,729.898621,10260550,0.008501,0.008466,728.903149,707.514794,729.238137,723.145551,0.008572,9,3,3
1,2021-09-17,784.500,794.500000,779.599976,791.075012,740.286011,20498102,0.014231,0.014131,730.520914,707.958832,730.937810,724.415215,0.008130,9,3,4
2,2021-09-20,782.000,790.849976,779.000000,779.924988,729.851807,8781610,-0.014095,-0.014195,731.576025,708.149266,730.770732,724.817925,0.008417,9,3,0
3,2021-09-21,781.000,784.325012,764.474976,775.974976,726.155396,14774996,-0.005065,-0.005077,732.215878,708.444044,730.060680,724.916997,0.008477,9,3,1
4,2021-09-22,774.500,775.075012,765.000000,766.849976,717.616211,10582202,-0.011759,-0.011829,731.627493,708.740692,728.146147,724.376198,0.008718,9,3,2

In [3]:
df.shape

(1189, 17)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1189 entries, 0 to 1188
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                1189 non-null   str
 1   Open                1189 non-null   float64
 2   High                1189 non-null   float64
 3   Low                 1189 non-null   float64
 4   Close               1189 non-null   float64
 5   Adj Close           1189 non-null   float64
 6   Volume              1189 non-null   int64
 7   Daily Return        1189 non-null   float64
 8   Log Return          1189 non-null   float64
 9   SMA_20              1189 non-null   float64
 10  SMA_50              1189 non-null   float64
 11  EMA_12              1189 non-null   float64
 12  EMA_26              1189 non-null   float64
 13  Rolling Volatility  1189 non-null   float64
 14  Month               1189 non-null   int64
 15  Quarter             1189 non-null   int64
 16  Day of Week         1189 non-null   int64
dtypes: float64(12), int64(4), str(1)
memory usage: 158.0 KB

In [5]:
df.isnull().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Adj Close             0
Volume                0
Daily Return          0
Log Return            0
SMA_20                0
SMA_50                0
EMA_12                0
EMA_26                0
Rolling Volatility    0
Month                 0
Quarter               0
Day of Week           0
dtype: int64

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Open,1189.0,8.203941e+02,9.056266e+01,637.500000,7.539500e+02,8.098500e+02,8.620000e+02,1.018850e+03
High,1189.0,8.274211e+02,9.052493e+01,648.200012,7.615000e+02,8.170000e+02,8.725000e+02,1.020500e+03
Low,1189.0,8.139177e+02,9.044524e+01,635.799988,7.478250e+02,8.025000e+02,8.552000e+02,1.008500e+03
Close,1189.0,8.206689e+02,9.033587e+01,640.650024,7.549500e+02,8.090750e+02,8.643500e+02,1.012900e+03
Adj Close,1189.0,7.897492e+02,9.671575e+01,606.489258,7.162092e+02,7.770703e+02,8.398688e+02,9.964198e+02
Volume,1189.0,2.768755e+07,2.550122e+07,0.000000,1.413726e+07,2.244158e+07,3.450221e+07,4.453421e+08
Daily Return,1189.0,2.033270e-04,1.323589e-02,-0.084358,-6.597922e-03,3.378580e-04,6.932752e-03,1.001327e-01
Log Return,1189.0,1.157172e-04,1.324635e-02,-0.088130,-6.619784e-03,3.378010e-04,6.908831e-03,9.543084e-02
SMA_20,1189.0,7.892498e+02,9.510805e+01,627.161252,7.168629e+02,7.716100e+02,8.331073e+02,9.833888e+02
SMA_50,1189.0,7.886183e+02,9.324358e+01,634.404601,7.169294e+02,7.687080e+02,8.419988e+02,9.795537e+02
EMA_12,1189.0,7.894414e+02,9.525473e+01,622.922516,7.156827e+02,7.728941e+02,8.369057e+02,9.874656e+02
EMA_26,1189.0,7.891345e+02,9.381993e+01,634.212543,7.199277e+02,7.724330e+02,8.340762e+02,9.805427e+02
Rolling Volatility,1189.0,1.244678e-02,4.399348e-03,0.005733,9.682715e-03,1.151673e-02,1.417748e-02,2.890957e-02
Month,1189.0,6.479394e+00,3.510296e+00,1.000000,3.000000e+00,6.000000e+00,1.000000e+01,1.200000e+01
Quarter,1189.0,2.489487e+00,1.133036e+00,1.000000,1.000000e+00,2.000000e+00,4.000000e+00,4.000000e+00
Day of Week,1189.0,2.000000e+00,1.417186e+00,0.000000,1.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00

In [7]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Return,Log Return,SMA_20,SMA_50,EMA_12,EMA_26,Rolling Volatility,Month,Quarter,Day of Week
0,2021-09-16,768.875,782.150024,768.150024,779.974976,729.898621,10260550,0.008501,0.008466,728.903149,707.514794,729.238137,723.145551,0.008572,9,3,3
1,2021-09-17,784.500,794.500000,779.599976,791.075012,740.286011,20498102,0.014231,0.014131,730.520914,707.958832,730.937810,724.415215,0.008130,9,3,4
2,2021-09-20,782.000,790.849976,779.000000,779.924988,729.851807,8781610,-0.014095,-0.014195,731.576025,708.149266,730.770732,724.817925,0.008417,9,3,0
3,2021-09-21,781.000,784.325012,764.474976,775.974976,726.155396,14774996,-0.005065,-0.005077,732.215878,708.444044,730.060680,724.916997,0.008477,9,3,1
4,2021-09-22,774.500,775.075012,765.000000,766.849976,717.616211,10582202,-0.011759,-0.011829,731.627493,708.740692,728.146147,724.376198,0.008718,9,3,2