# Data Collection

## Objective

Download historical stock data from Yahoo Finance.

Ticker: RELIANCE.NS

Period: 5 Years

Data Source: Yahoo Finance

In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import yfinance as yf

ticker = "RELIANCE.NS"

df = yf.download(
    ticker,
    period="5y",
    auto_adjust=False,
    progress=False
)

df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2021-07-08,947.776001,965.734558,976.972107,960.381165,976.972107,11185460
2021-07-09,938.083557,955.858459,965.319214,953.504822,963.611633,9037675
2021-07-12,943.926270,961.811829,969.841919,957.381409,959.804260,8585292
2021-07-13,950.991821,969.011230,970.557251,963.634705,969.149658,6717133
2021-07-14,944.786804,962.688660,972.310913,960.496521,969.311157,8532544

In [3]:
df.tail()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2026-07-02,1303.500000,1303.500000,1313.199951,1299.000000,1310.0,17795024
2026-07-03,1304.000000,1304.000000,1312.000000,1302.000000,1312.0,7839550
2026-07-06,1321.300049,1321.300049,1325.599976,1299.400024,1304.0,7610709
2026-07-07,1308.400024,1308.400024,1328.000000,1304.099976,1323.5,14335554
2026-07-08,1275.900024,1275.900024,1302.300049,1271.599976,1297.0,19955877

In [4]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1238 entries, 2021-07-08 to 2026-07-08
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Adj Close, RELIANCE.NS)  1238 non-null   float64
 1   (Close, RELIANCE.NS)      1238 non-null   float64
 2   (High, RELIANCE.NS)       1238 non-null   float64
 3   (Low, RELIANCE.NS)        1238 non-null   float64
 4   (Open, RELIANCE.NS)       1238 non-null   float64
 5   (Volume, RELIANCE.NS)     1238 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 67.7 KB